# Site settings
## Change the values as needed.
title: NitroKIR IT
email: 
description: "A division of KIR that computes and creates."
keywords: "nitrokir"
#url: "http://bitwiser.in/bitwiser-material" # the base hostname & protocol for your site
url: "http://nitrokir-it.github.io" # the base hostname & protocol for your site
baseurl: "/" # the subpath of your site, e.g. /blog/
paginate: 10
paginate_path: "page:num"
# Build settings
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist, github-pages]
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
links:
  facebook: 
  twitter: 
  email: 
  github: 
exclude:
  - bower_components
  - README.md
full_name: 

##set this to enable disqus commenting
disqus: nitrokir-it

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: bitwiser.in
