title: NitroKIR IT
description: KIR divisi IT SMAN 2
author: nitrokir-it
logo: 
github: https://github.com/NitroKIR-IT
about: 

baseurl: ""
url: "http://nitrokir-it.github.io"

disqus_shortname: 
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
